
title: Where Sungmin Writes
email: woos8899@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  취미로 프로그래밍을 하는 대학생입니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: Sungmin Woo
  email: woos8899@gmail.com

minima:
  social_links:
    twitter: woos8899
    github: SausageTaste
    steam: sausagetaste

disqus:
  shortname: sausagetaste

theme: minima
markdown: kramdown
plugins:
  - jekyll-feed

host: 0.0.0.0
github_pages_url: "https://sausagetaste.github.io"
