
title: Where Sungmin Writes
email: woos8899@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  C++와 OpenGL로 게임엔진을 개발하고 있으며 취미로 그림을 그리고 대학에서 경제학을 전공하고 있습니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: Sungmin Woo
  email: woos8899@gmail.com

minima:
  social_links:
    twitter: woos8899
    github: SausageTaste
    steam: sausagetaste

disqus:
  shortname: sausagetaste

# Build settings
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed

host: 0.0.0.0

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
